[package]
name = "server"
version.workspace = true
edition.workspace = true


[dependencies]

# not wasm dependencies
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { workspace = true, features = ["full"] }
